# ====== DATABASE ======
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker_dev
spring.datasource.username=expense_user
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect