# ======= PROFILE =======
# spring.profiles.active=dev

# ====== ADMIN CRED =====
ADMIN_USERNAME=superadmin
ADMIN_PASSWORD=adminPass123
ADMIN_EMAIL=admin@example.com

# ======= APP =======
spring.application.name=Expense Tracker API
server.port=9000

# ====== JWT =======
jwt.secret=MyVerySecretKeyForJWTTokensMustBeAtLeast256BitsLongForHS512Algorithm
jwt.expiration=86400000

# ======= LOGGING ========
logging.level.root=INFO
logging.level.com.elm.expensetracker=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.file.name=logs/expense-tracker.log

logging.logback.rollingpolicy.file-name-pattern=logs/expense-tracker.%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

# ====== PROFILING =======
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.health.show-components=when_authorized

management.info.env.enabled=true
info.app.name=Expense Tracker API
info.app.description=API for tracking expenses
info.app.version=0.0.1




